name: 功能请求
description: 若是有在下能力所能及的事情，还请主人吩咐 ♪
title: "[FEAT] <title>"
labels:
  - enhancement
assignees:
  - xueelf
body:
  - type: markdown
    attributes:
      value: |
        感谢你的问题反馈，为了方便更快的定位问题，建议尽可能多地填写以下表格。(\*^▽^\*)

        该 issue 将被用于程序中的新功能开发，在这之前请先确认 kokkoro 是否已存在类似插件哦。若你想要获取更多插件，可以先 [查阅文档](https://kokkoro.js.org/plugin/awesome)。
  - type: textarea
    attributes:
      label: 功能描述
      description: 阐述相关功能点，最好能提供伪代码示例
    validations:
      required: true
  - type: textarea
    attributes:
      label: 有没有类似的轮子或者现有的解决方案？
      description: 提供仓库地址将加快功能的开发
